package com.barracudatrial.game.route;

import net.runelite.api.coords.WorldPoint;
import net.runelite.api.gameval.ObjectID;

import java.util.List;
import java.util.Set;

public class GwenithGlideConfig implements TrialConfig
{
	public static final int BOAT_EXCLUSION_WIDTH = 4;
	public static final int BOAT_EXCLUSION_HEIGHT = 8;

	// Crystal motes - wind motes that provide speed boosts and crystal immunity
	public static final int CRYSTAL_MOTE_ID = ObjectID.SAILING_BT_GWENITH_GLIDE_MOTE; // 58980

	// Resonance crystals - the crystals that spawn white spikes
	public static final Set<Integer> RESONANCE_CRYSTAL_IDS = Set.of(
		ObjectID.SAILING_BT_GWENITH_GLIDE_CRYSTAL, // 58978
		ObjectID.SAILING_BT_GWENITH_GLIDE_CRYSTAL_2 // 58979
	);

	// Portal teleport markers
	public static final Set<Integer> PORTAL_IDS = Set.of(
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_ITHELL, // 59086
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_AMLODD, // 59087
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_CADARN, // 59088
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_CRWYS, // 59089
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_HEFIN, // 59090
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_IORWERTH, // 59091
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_MEILYR, // 59092
		ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_TRAHAEARN // 59093
	);

	// Portal locations with exact WorldPoints
	public static final GwenithGlidePortal[] PORTALS =
	{
		// TODO: Capture portal location for Ithell
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_ITHELL,
				"Ithell"
		),
		// TODO: Capture portal location for Amlodd
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_AMLODD,
				"Amlodd"
		),
		// TODO: Capture portal location for Cadarn
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_CADARN,
				"Cadarn"
		),
		// TODO: Capture portal location for Crwys
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_CRWYS,
				"Crwys"
		),
		// TODO: Capture portal location for Hefin
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_HEFIN,
				"Hefin"
		),
		// TODO: Capture portal location for Iorwerth
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_IORWERTH,
				"Iorwerth"
		),
		// TODO: Capture portal location for Meilyr
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_MEILYR,
				"Meilyr"
		),
		// TODO: Capture portal location for Trahaearn
		new GwenithGlidePortal(
				new WorldPoint(0, 0, 0),
				ObjectID.SAILING_BT_GWENITH_GLIDE_TELEPORT_MARKER_TRAHAEARN,
				"Trahaearn"
		)
	};

	// Lost supplies - collectables scattered throughout the trial
	private static final Set<Integer> SHIPMENT_IDS = Set.of(
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_1, // 58982
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_2,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_3,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_4,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_5,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_6,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_7,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_8,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_9,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_10,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_11,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_12,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_13,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_14,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_15,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_16,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_17,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_18,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_19,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_20,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_21,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_22,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_23,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_24,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_25,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_26,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_27,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_28,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_29,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_30,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_31,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_32,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_33,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_34,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_35,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_36,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_37,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_38,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_39,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_40,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_41,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_42,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_43,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_44,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_45,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_46,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_47,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_48,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_49,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_50,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_51,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_52,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_53,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_54,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_55,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_56,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_57,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_58,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_59,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_60,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_61,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_62,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_63,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_64,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_65,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_66,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_67,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_68,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_69,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_70,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_71,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_72,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_73,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_74,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_75,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_76,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_77,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_78,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_79,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_80,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_81,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_82,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_83,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_84,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_85,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_86,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_87,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_88,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_89,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_90,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_91,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_92,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_93,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_94,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_95,
			ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_96 // 59077
	);

	private static final int SHIPMENT_IMPOSTOR_ID = ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_SUPPLIES; // 58981

	// TODO: Verify if Gwenith uses same rock IDs as other trials
	private static final Set<Integer> ROCK_IDS = Set.of(
		59314, 59315, 60437, 60438, 60440, 60441, 60442, 60443, 60444
	);

	private static final Set<Integer> SPEED_BOOST_IDS = Set.of(
		ObjectID.SAILING_RAPIDS_STRONG
	);

	@Override
	public TrialType getTrialType()
	{
		return TrialType.GWENITH_GLIDE;
	}

	@Override
	public Set<Integer> getShipmentBaseIds()
	{
		return SHIPMENT_IDS;
	}

	@Override
	public int getShipmentImpostorId()
	{
		return SHIPMENT_IMPOSTOR_ID;
	}

	@Override
	public Set<Integer> getRockIds()
	{
		return ROCK_IDS;
	}

	@Override
	public Set<Integer> getSpeedBoostIds()
	{
		return SPEED_BOOST_IDS;
	}

	@Override
	public List<RouteWaypoint> getRoute(Difficulty difficulty)
	{
		return GwenithGlideRoutes.getRoute(difficulty);
	}
}
